# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("JetBrainsMono Nerd Font Mono")
        font.setPointSize(12)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 10, 761, 561))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.filename_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.filename_label.setStyleSheet("color: #000;\n"
"background-color: #fff;\n"
"border: none;\n"
"padding: 2px;\n"
"font-family: \"Arial\";\n"
"font-size: 16px;")
        self.filename_label.setText("")
        self.filename_label.setObjectName("filename_label")
        self.verticalLayout.addWidget(self.filename_label)
        self.textspace_edit = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.textspace_edit.setStyleSheet("color: #000;\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"font-family: \"Arial\";\n"
"font-size: 18px;")
        self.textspace_edit.setReadOnly(True)
        self.textspace_edit.setObjectName("textspace_edit")
        self.verticalLayout.addWidget(self.textspace_edit)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.selectFile_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.selectFile_btn.setStyleSheet("color: #000;\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"padding: 3px;\n"
"font-family: \"Arial\";\n"
"font-size: 18px;\n"
"border-radius: 5px;")
        self.selectFile_btn.setObjectName("selectFile_btn")
        self.horizontalLayout.addWidget(self.selectFile_btn)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.deobfuscate_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.deobfuscate_btn.setStyleSheet("color: #000;\n"
"background-color: #fff;\n"
"border: 1px solid #000;\n"
"padding: 3px;\n"
"font-family: \"Arial\";\n"
"font-size: 18px;\n"
"border-radius: 5px;")
        self.deobfuscate_btn.setObjectName("deobfuscate_btn")
        self.verticalLayout.addWidget(self.deobfuscate_btn)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Python-Deobfuscation-Multi-Tool"))
        self.selectFile_btn.setText(_translate("MainWindow", "Select file"))
        self.deobfuscate_btn.setText(_translate("MainWindow", "Deobfuscate"))
